content_page:
    pages:
        blog_article:
            path: '/blog/{id}'
            service: 'blog-articles'
        scholarly_article:
            handler: 'jats'
            path: '/articles/{id}'
            service: 'scholarly-articles'
