content_page:
    pages:
        home_page:
            path: '/'
            service: 'scholarly-articles'
        blog_article:
            path: '/blog/{id}'
            service: 'blog-articles'
        scholarly_article:
            path: '/articles/{id}'
            service: 'scholarly-articles'
