libero_page:
    pages:
        homepage:
            type: homepage
            path: '/'
            content_service: 'scholarly-articles'
        blog_article:
            type: content
            path: '/blog/{id}'
            content_service: 'blog-articles'
        scholarly_article:
            type: content
            path: '/articles/{id}'
            content_service: 'scholarly-articles'
