libero_page:
    pages:
        homepage:
            path: '/'
        content:
            blog_article:
                path: '/blog/{id}'
                content_service: 'blog-articles'
            scholarly_article:
                path: '/articles/{id}'
                content_service: 'scholarly-articles'
